namespace TMC.Domain.Attributes;

[AttributeUsage(AttributeTargets.Property)]
public class DbPropertyNameAttribute : Attribute
{
    public DbPropertyNameAttribute(string propertyName, bool isNested = false, bool isAutoGenerated = false)
    {
        PropertyName = propertyName;
        IsNested = isNested;
        IsAutoGenerated = isAutoGenerated;
    }

    public string PropertyName { get; set; }

    /// <summary>
    ///     Does the property require a path to be retrieved or it is a direct property of the node
    /// </summary>
    public bool IsNested { get; set; }

    public bool IsAutoGenerated { get; set; }
}